#!/usr/bin/env python3
"""Build offline PDF fonts from the same pinned font assets used by the web UI.

Run from the repository root; see README.md for the project-local uv invocation.
"""
from base64 import b64encode
from hashlib import sha256
from io import BytesIO
from pathlib import Path
import json

from fontTools.merge import Merger
from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parents[4]
ASSETS = Path(__file__).resolve().parent
WORK = ROOT / '.agent-work/20260918-document-design/tmp/fonts'
SOURCES = {
    'latin': ROOT / 'node_modules/@fontsource-variable/dm-sans/files/dm-sans-latin-wght-normal.woff2',
    'thai': ROOT / 'node_modules/@fontsource-variable/noto-sans-thai/files/noto-sans-thai-thai-wght-normal.woff2',
}


def static_subset(source: Path, weight: int, thai: bool, output: Path) -> None:
    font = TTFont(source, recalcTimestamp=False)
    axes = {axis.axisTag: axis.defaultValue for axis in font['fvar'].axes}
    axes['wght'] = weight
    font = instantiateVariableFont(font, axes, inplace=True)
    font.flavor = None
    # No codepoint overlap: Latin, punctuation and numerals come from DM Sans.
    # Keep Thai mark layout closure (GSUB/GPOS/GDEF) and the dotted-circle base.
    codepoints = set(font.getBestCmap())
    keep = {cp for cp in codepoints if (0x0E00 <= cp <= 0x0E7F or cp == 0x25CC)} if thai else codepoints - {0x25CC}
    options = Options()
    options.layout_features = ['*']
    subsetter = Subsetter(options=options)
    subsetter.populate(unicodes=keep)
    subsetter.subset(font)
    font.save(output)


def build(weight: int, style: str) -> bytes:
    parts = []
    for key, source in SOURCES.items():
        output = WORK / f'{key}-{weight}.ttf'
        static_subset(source, weight, key == 'thai', output)
        parts.append(str(output))
    font = Merger().merge(parts)
    font.recalcTimestamp = False
    family = 'Labs D Document'
    names = {
        1: family, 2: style, 3: f'LabsDDocument-{style}-1.0',
        4: f'{family} {style}', 6: f'LabsDDocument-{style}',
        16: family, 17: style,
        0: 'DM Sans: Copyright 2014 The DM Sans Project Authors. Noto Sans Thai: Copyright 2022 The Noto Project Authors.',
        13: 'Licensed under the SIL Open Font License, Version 1.1. See bundled OFL license files.',
        14: 'https://openfontlicense.org',
    }
    for name_id, text in names.items():
        font['name'].removeNames(nameID=name_id)
        font['name'].setName(text, name_id, 3, 1, 0x409)
    font['OS/2'].usWeightClass = weight
    # Stable build metadata; do not inject local generation time into the bytes.
    font['head'].created = font['head'].modified = 3786912000
    required = set(range(0x0E01, 0x0E3B)) | set(range(0x0E3F, 0x0E5C)) | set(map(ord, 'Labs D 25,000.00'))
    assert required <= set(font.getBestCmap()), 'Required Thai/Latin glyphs missing'
    assert {'GSUB', 'GPOS', 'GDEF'} <= set(font.keys()), 'Thai shaping tables missing'
    buf = BytesIO()
    font.save(buf)
    data = buf.getvalue()
    (WORK / f'LabsDDocument-{style}.ttf').write_bytes(data)
    return data


def main() -> None:
    WORK.mkdir(parents=True, exist_ok=True)
    lines = [
        '// Generated by generate-document-fonts.py; do not edit manually.',
        '// DM Sans Latin + Noto Sans Thai, SIL OFL-1.1. See README.md and OFL-*.txt.',
        '// Static TrueType fonts preserve Thai GSUB/GPOS/GDEF shaping tables.',
        '',
    ]
    manifest = {'sources': {name: {'path': str(path.relative_to(ROOT)), 'sha256': sha256(path.read_bytes()).hexdigest()} for name, path in SOURCES.items()}, 'outputs': {}}
    for weight, style, symbol in [(400, 'Regular', 'documentRegularBase64'), (600, 'SemiBold', 'documentSemiBoldBase64')]:
        data = build(weight, style)
        encoded = b64encode(data).decode('ascii')
        lines.append(f"export const {symbol} = '{encoded}';")
        lines.append('')
        manifest['outputs'][symbol] = {'weight': weight, 'bytes': len(data), 'sha256': sha256(data).hexdigest()}
    (ASSETS / 'document-fonts.ts').write_text('\n'.join(lines))
    (ASSETS / 'font-manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    for package, label in [('dm-sans', 'DM-Sans'), ('noto-sans-thai', 'Noto-Sans-Thai')]:
        (ASSETS / f'OFL-{label}.txt').write_bytes((ROOT / f'node_modules/@fontsource-variable/{package}/LICENSE').read_bytes())
    print(json.dumps(manifest['outputs'], indent=2))


if __name__ == '__main__':
    main()
