const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',video:'<rect x="3" y="5" width="13" height="14" rx="3"/><path d="m16 10 5-3v10l-5-3"/>',wallet:'<rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 8h18M17 12h4v5h-4a2.5 2.5 0 0 1 0-5Z"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-2 7-2 9h16c0-2-2-2-2-9M10 21h4"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 5M12 17h.01"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M4 15v5h16v-5"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4M17 3v4M3 11h18"/>',chevron:'<path d="m8 10 4 4 4-4"/>',reset:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7"/>',arrow:'<path d="M6 18 18 6M6 6h12v12"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>',verified:'<path d="m12 2 3 2 4 1 1 4 2 3-2 3-1 4-4 1-3 2-3-2-4-1-1-4-2-3 2-3 1-4 4-1Z"/><path d="m8 12 3 3 5-6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>'};
function renderIcons(){document.querySelectorAll('[data-icon]').forEach(el=>{el.outerHTML=`<svg class="icon" aria-hidden="true" viewBox="0 0 24 24">${icons[el.dataset.icon]||icons.grid}</svg>`})}
const clips=[
{id:1,title:'พูดตรง ๆ ตัวนี้ช่วยให้เช้าวันทำงานง่ายขึ้น',brand:'Axtion',date:'2026-08-28',views:812000,sales:128000,rate:.1,status:'pending',type:'Organic'},
{id:2,title:'3 นาทีหลังตื่นนอน กับ routine ที่ทำให้สดขึ้น',brand:'Axtion',date:'2026-08-21',views:641000,sales:104000,rate:.03,status:'pending',type:'Brand ads'},
{id:3,title:'ลองให้ดูแบบไม่สปอนเซอร์ ถ้าไม่ดีไม่พูด',brand:'Tendrix',date:'2026-08-14',views:588000,sales:96000,rate:.1,status:'pending',type:'Organic'},
{id:4,title:'ของดีบอกต่อ: เปิดกล่องแล้วชอบตรงไหน',brand:'Rusiren',date:'2026-08-07',views:420000,sales:86000,rate:.03,status:'paid',type:'Brand ads'},
{id:5,title:'รีวิวแบบคนใช้จริง ดูผิวในแสงธรรมชาติ',brand:'Melura',date:'2026-07-31',views:391000,sales:74000,rate:.1,status:'paid',type:'Organic'},
{id:6,title:'ตัวเดียวจบสำหรับวันที่ต้องออกกอง',brand:'Zenova',date:'2026-07-24',views:284000,sales:62000,rate:.03,status:'paid',type:'Brand ads'}
].map(c=>({...c,commission:Math.round(c.sales*c.rate),cover:'./assets/clip-cover-'+c.id+'.png',coverPosition:c.id===5?'43% 50%':'50% 50%'}));
const money=n=>'฿'+n.toLocaleString('en-US');const number=n=>n.toLocaleString('en-US');const sum=(rows,key)=>rows.reduce((n,c)=>n+c[key],0);const $=id=>document.getElementById(id);
const dateLabel=date=>new Date(date+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short'});
function selected(){return clips.filter(c=>($('brand').value==='all'||c.brand===$('brand').value)&&($('period').value==='all'||c.date.startsWith($('period').value==='aug'?'2026-08':'2026-07')))}
function showPage(page){document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==page);document.querySelectorAll('.nav').forEach(b=>{const active=b.dataset.page===page;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});document.querySelectorAll('.rail [data-page]').forEach(b=>b.classList.toggle('rail-active',b.dataset.page===page));const meta={overview:['Overview','Your content <span>Your impact</span>','ทุกคอนเทนต์มีคุณค่า ติดตามยอดขายและคอมมิชชันของคุณได้ในที่เดียว'],clips:['My content','Create Share <span>Get rewarded</span>','ดูผลงานและคอมมิชชันของแต่ละคลิปในมุมมองเดียว'],payouts:['Transactions','Your earnings <span>All clear</span>','ติดตามคอมมิชชันรอจ่ายและยอดที่ได้รับแล้ว']};$('page-title').innerHTML=meta[page][1];$('page-subtitle').textContent=meta[page][2];window.scrollTo({top:0,behavior:'instant'});}
function drawTrend(rows){
 const sorted=[...rows].sort((a,b)=>a.date.localeCompare(b.date));
 const w=Math.max(160,$('trend-chart').clientWidth),h=180,left=35,right=34,top=34,bottom=32,plotH=h-top-bottom;
 const max=Math.max(15000,...sorted.map(c=>c.commission));
 let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="กราฟคอมมิชชันรายคลิป ตัวเลขเดียวกับรายการคลิป"><defs><linearGradient id="trend-line-gradient" gradientUnits="userSpaceOnUse" x1="${left}" y1="0" x2="${w-right}" y2="0"><stop offset="0%" stop-color="#ccf66a"/><stop offset="100%" stop-color="#32c96b"/></linearGradient><linearGradient id="trend-green-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#ccf66a" stop-opacity=".18"/><stop offset="60%" stop-color="#ccf66a" stop-opacity=".07"/><stop offset="100%" stop-color="#ccf66a" stop-opacity="0"/></linearGradient></defs>`;
 [0,.5,1].forEach(v=>{const y=top+plotH*(1-v);svg+=`<line x1="${left}" x2="${w-right}" y1="${y}" y2="${y}" stroke="#e0e3d9" stroke-dasharray="3 5"/><text x="0" y="${y+5}" fill="#5f6558" font-size="14">${Math.round(max*v/1000)}k</text>`});
 if(!sorted.length){svg+=`<text x="${w/2}" y="90" text-anchor="middle" fill="#5f6558" font-size="14">ไม่มีข้อมูลในช่วงที่เลือก</text>`}
 else{
  const points=sorted.map((c,i)=>({x:sorted.length===1?w/2:left+i*(w-left-right)/(sorted.length-1),y:top+plotH*(1-c.commission/max),c}));
  // Horizontal tangents keep each curve inside its two measured endpoints.
  const path=points.map((p,i)=>{if(!i)return `M${p.x},${p.y}`;const previous=points[i-1],midX=(previous.x+p.x)/2;return `C${midX},${previous.y} ${midX},${p.y} ${p.x},${p.y}`}).join(' ');
  svg+=`<path class="trend-area" d="${path} L${points.at(-1).x},${top+plotH} L${points[0].x},${top+plotH} Z" fill="url(#trend-green-fill)"/><path class="trend-line" pathLength="1" d="${path}" fill="none" stroke="url(#trend-line-gradient)" stroke-width="1.8" stroke-linejoin="round" stroke-linecap="round"/>`;
  const tickStep=Math.max(1,Math.ceil(64*(points.length-1)/(w-left-right)));
  points.forEach((p,i)=>{svg+=`<circle class="trend-point" cx="${p.x}" cy="${p.y}" r="3.5" fill="#333c29"><title>${p.c.title}: ${money(p.c.commission)}</title></circle>`;if(i===points.length-1||(i%tickStep===0&&points.length-1-i>=tickStep))svg+=`<text x="${p.x}" y="${h-6}" text-anchor="middle" fill="#5f6558" font-size="14">${dateLabel(p.c.date)}</text>`});
  const best=points.reduce((a,b)=>a.c.commission>b.c.commission?a:b),bx=Math.min(w-84,Math.max(32,best.x-40));
  svg+=`<rect x="${bx}" y="${best.y-31}" rx="7" width="80" height="25" fill="#ccf66a"/><text x="${bx+40}" y="${best.y-13}" text-anchor="middle" fill="#394926" font-size="14" font-weight="500">${money(best.c.commission)}</text>`;
 }
 return svg+'</svg>';
}
function row(c){return `<button class="clip-row" data-clip="${c.id}" aria-label="รายละเอียด ${c.title}"><img class="thumb" src="${c.cover}" alt="" loading="lazy" style="object-position:${c.coverPosition}"><div class="clip-name"><strong>${c.title}</strong><small>${c.brand} <span>·</span> ${c.type}</small></div><div class="amount">${money(c.commission)}<small>คอมมิชชัน</small></div><i data-icon="arrow"></i></button>`}
function update(){const rows=selected(),total=sum(rows,'commission'),organic=sum(rows.filter(c=>c.type==='Organic'),'commission'),ads=total-organic,pending=sum(rows.filter(c=>c.status==='pending'),'commission');$('total-commission').innerHTML=`<span class="currency">฿</span>${number(total)}`;$('trend-total').textContent=money(total);$('total-sales').textContent=money(sum(rows,'sales'));$('organic-commission').textContent=money(organic);$('ads-commission').textContent=money(ads);$('pending-total').textContent=money(pending);$('clip-count').textContent=rows.length;$('trend-chart').innerHTML=drawTrend(rows);const byBrand=['Axtion','Tendrix','Rusiren','Melura','Zenova'].map(brand=>({brand,sales:sum(rows.filter(c=>c.brand===brand),'sales')}));const max=Math.max(1,...byBrand.map(b=>b.sales));$('sales-chart').innerHTML=byBrand.map(b=>`<div class="bar-col"><div class="bar ${b.sales===max?'highlight':''}" style="--bar-size:${Math.max(3,b.sales/max*83)}%;height:var(--bar-size)" title="${b.brand}: ${money(b.sales)}">${b.sales===max?`<b class="bar-value">${Math.round(b.sales/1000)}k</b>`:''}</div><span>${b.brand}</span></div>`).join('');$('top-clips').innerHTML=rows.length?[...rows].sort((a,b)=>b.commission-a.commission).slice(0,3).map(row).join(''):'<p class="empty">ไม่มีคลิปในช่วงที่เลือก</p>';const share=total?Math.round(organic/total*100):0;$('organic-share').textContent=share+'%';$('donut').style.background=total?`conic-gradient(#92ed7e 0deg,#40d26a ${share*1.8}deg,#119b5c ${share*3.6}deg,#073d30 ${share*3.6}deg 360deg)`:'#e3e6dc';$('payment-stats').innerHTML=`<div><small>รอจ่าย · ตัวอย่าง</small><strong>${money(pending)}</strong></div><div><small>จ่ายแล้ว · ตัวอย่าง</small><strong>${money(total-pending)}</strong></div>`;$('payments').innerHTML=rows.length?rows.map(c=>`<tr role="row"><td role="cell">${c.title}<small>${c.brand} · DEMO-${String(c.id).padStart(3,'0')}</small></td><td role="cell" data-label="วันที่เผยแพร่">${dateLabel(c.date)} 2026</td><td role="cell" data-label="ประเภท">${c.type} · ${c.rate*100}%</td><td role="cell" data-label="คอมมิชชัน"><strong>${money(c.commission)}</strong></td><td role="cell" data-label="สถานะ"><span class="status ${c.status}">${c.status==='paid'?'จ่ายแล้ว':'รอจ่าย'}</span></td></tr>`).join(''):'<tr><td colspan="5" class="empty">ไม่มีรายการในช่วงที่เลือก</td></tr>';renderLibrary();renderIcons();}
function renderLibrary(){const q=$('search').value.toLowerCase().trim();const rows=selected().filter(c=>(c.title+c.brand).toLowerCase().includes(q));$('clip-library').innerHTML=rows.length?rows.map(c=>`<button class="clip-tile" data-clip="${c.id}"><div class="clip-art"><img src="${c.cover}" alt="ภาพปกคลิป ${c.brand}" loading="lazy" style="object-position:${c.coverPosition}"><span>${c.brand} · ตัวอย่างภาพประกอบ</span></div><h3>${c.title}</h3><div class="clip-meta">${dateLabel(c.date)} 2026 · ${number(c.views/1000)}K views</div><div class="clip-earnings"><span>${c.type} · ${c.rate*100}%</span><strong>${money(c.commission)}</strong></div></button>`).join(''):'<p class="empty">ไม่พบคลิป ลองเปลี่ยนคำค้นหาหรือตัวกรอง</p>'}
let previousFocus;function dialog(html){previousFocus=document.activeElement;$('detail-body').innerHTML=html;$('detail').showModal()};$('detail').addEventListener('close',()=>previousFocus?.focus());$('close-dialog').onclick=()=>$('detail').close();$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('detail').close()}});
document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page){e.preventDefault();showPage(page.dataset.page);return}const clip=e.target.closest('[data-clip]');if(clip){const c=clips.find(c=>c.id===Number(clip.dataset.clip));dialog(`<h2>${c.title}</h2><p>${c.brand} · ${dateLabel(c.date)} 2026 · ข้อมูลตัวอย่าง</p><div class="detail-stat"><span>ยอดขายจากคลิป</span><strong>${money(c.sales)}</strong></div><div class="detail-stat"><span>อัตรา ${c.type}</span><strong>${c.rate*100}%</strong></div><div class="detail-stat"><span>คอมมิชชัน</span><strong>${money(c.commission)}</strong></div><p class="dialog-note">${money(c.sales)} × ${c.rate*100}% = ${money(c.commission)}<br>ตัวเลขสำหรับดูแบบ UI เท่านั้น ไม่ใช่ยอดรับเงินจริง</p>`)}});
$('period').onchange=update;$('brand').onchange=update;$('reset').onclick=()=>{$('period').value='all';$('brand').value='all';$('search').value='';update()};$('search').oninput=renderLibrary;
$('model').onclick=()=>dialog('<h2>Every earning, explained.</h2><p>ตัวอย่างวิธีแสดงอัตราคอมมิชชันจากหน้าเดิม</p><div class="detail-stat"><span>Organic content</span><strong>10%</strong></div><div class="detail-stat"><span>Brand ads</span><strong>3%</strong></div><p class="dialog-note">ยอดขายของคลิป × อัตราคอมมิชชัน<br>นี่เป็นแบบหน้าตา ระบบจริงต้องใช้เงื่อนไขจากสัญญาและข้อมูลยอดขายที่ยืนยันแล้ว</p>');
const demoNotifications=[
 'มีคลิป Axtion ใหม่ใน My content',
 'อัปเดตสรุปคอมมิชชันประจำเดือนสิงหาคม',
 'ยินดีต้อนรับสู่ Labs D x Partner'
];
const notificationCount=demoNotifications.length;
$('notification-count').textContent=notificationCount>99?'99+':notificationCount;
$('notification-count').hidden=notificationCount===0;
$('notifications').setAttribute('aria-label',notificationCount?'การแจ้งเตือน '+notificationCount+' รายการ':'การแจ้งเตือน');
$('notifications').onclick=()=>dialog('<h2>การแจ้งเตือน</h2><p>ข้อมูลตัวอย่าง · '+notificationCount+' รายการ</p>'+demoNotifications.map(message=>'<div class="notification-item">'+message+'</div>').join(''));
$('account').onclick=()=>dialog('<h2>มดดำ คชาภา</h2><p>Celebrity partner · บัญชีตัวอย่าง<br>หน้าตาหลังเข้าสู่ระบบ ยังไม่ได้เชื่อมระบบล็อกอิน</p>');$('help').onclick=()=>dialog('<h2>Your partner, every step.</h2><p>ตัวอย่างพื้นที่ช่วยเหลือสำหรับคู่ค้า<br>ระบบจริงสามารถใส่ข้อมูลผู้ดูแลและช่องทางติดต่อทีม Labs D ได้ที่นี่</p>');
$('export').onclick=()=>dialog('<h2>Your report, at a glance.</h2><p>ตัวอย่างสรุปรายงานตามตัวกรองที่เลือก</p><div class="detail-stat"><span>คลิปทั้งหมด</span><strong>'+selected().length+'</strong></div><div class="detail-stat"><span>ยอดขาย</span><strong>'+money(sum(selected(),'sales'))+'</strong></div><div class="detail-stat"><span>คอมมิชชัน</span><strong>'+money(sum(selected(),'commission'))+'</strong></div><p class="dialog-note">ปุ่มนี้แสดงตัวอย่างรายงานเพื่อดูดีไซน์ ยังไม่ได้เชื่อมการส่งออกไฟล์จริง</p>');
$('mobile-help').onclick=()=> $('help').click();
update();showPage('overview');

let chartWidth=0;const chartResize=new ResizeObserver(()=>{const width=$('trend-chart').clientWidth;if(width>0&&width!==chartWidth){chartWidth=width;$('trend-chart').innerHTML=drawTrend(selected())}});chartResize.observe($('trend-chart'));
